/*!
## Problem 2. Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

pub fn answer() -> i32 {
    let mut a = 1;
    let mut b = 2;

    let mut running_even_sum = b;
    let mut ab = 0;
    while ab < 4000000 {
        ab = a + b;
        a = b;
        b = ab;

        if ab % 2 == 0 {
            running_even_sum += ab;
        }
    }

    running_even_sum
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_answer() {
        assert_eq!(answer(), 4613732)
    }
}
